// Code generated by protoc-gen-go.
// source: google/protobuf/api.proto
// DO NOT EDIT!

/*
Package descriptor is a generated protocol buffer package.

It is generated from these files:
	google/protobuf/api.proto
	google/protobuf/descriptor.proto
	google/protobuf/source_context.proto
	google/protobuf/type.proto

It has these top-level messages:
	Api
	Method
	Mixin
	FileDescriptorSet
	FileDescriptorProto
	DescriptorProto
	FieldDescriptorProto
	OneofDescriptorProto
	EnumDescriptorProto
	EnumValueDescriptorProto
	ServiceDescriptorProto
	MethodDescriptorProto
	FileOptions
	MessageOptions
	FieldOptions
	OneofOptions
	EnumOptions
	EnumValueOptions
	ServiceOptions
	MethodOptions
	UninterpretedOption
	SourceCodeInfo
	GeneratedCodeInfo
	SourceContext
	Type
	Field
	Enum
	EnumValue
	Option
*/
package descriptor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Api is a light-weight descriptor for a protocol buffer service.
type Api struct {
	// The fully qualified name of this api, including package name
	// followed by the api's simple name.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The methods of this api, in unspecified order.
	Methods []*Method `protobuf:"bytes,2,rep,name=methods" json:"methods,omitempty"`
	// Any metadata attached to the API.
	Options []*Option `protobuf:"bytes,3,rep,name=options" json:"options,omitempty"`
	// A version string for this api. If specified, must have the form
	// `major-version.minor-version`, as in `1.10`. If the minor version
	// is omitted, it defaults to zero. If the entire version field is
	// empty, the major version is derived from the package name, as
	// outlined below. If the field is not empty, the version in the
	// package name will be verified to be consistent with what is
	// provided here.
	//
	// The versioning schema uses [semantic
	// versioning](http://semver.org) where the major version number
	// indicates a breaking change and the minor version an additive,
	// non-breaking change. Both version numbers are signals to users
	// what to expect from different versions, and should be carefully
	// chosen based on the product plan.
	//
	// The major version is also reflected in the package name of the
	// API, which must end in `v<major-version>`, as in
	// `google.feature.v1`. For major versions 0 and 1, the suffix can
	// be omitted. Zero major versions must only be used for
	// experimental, none-GA apis.
	//
	//
	Version string `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
	// Source context for the protocol buffer service represented by this
	// message.
	SourceContext *SourceContext `protobuf:"bytes,5,opt,name=source_context,json=sourceContext" json:"source_context,omitempty"`
	// Included APIs. See [Mixin][].
	Mixins []*Mixin `protobuf:"bytes,6,rep,name=mixins" json:"mixins,omitempty"`
	// The source syntax of the service.
	Syntax Syntax `protobuf:"varint,7,opt,name=syntax,enum=google.protobuf.Syntax" json:"syntax,omitempty"`
}

func (m *Api) Reset()                    { *m = Api{} }
func (m *Api) String() string            { return proto.CompactTextString(m) }
func (*Api) ProtoMessage()               {}
func (*Api) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Api) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

func (m *Api) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Api) GetSourceContext() *SourceContext {
	if m != nil {
		return m.SourceContext
	}
	return nil
}

func (m *Api) GetMixins() []*Mixin {
	if m != nil {
		return m.Mixins
	}
	return nil
}

// Method represents a method of an api.
type Method struct {
	// The simple name of this method.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// A URL of the input message type.
	RequestTypeUrl string `protobuf:"bytes,2,opt,name=request_type_url,json=requestTypeUrl" json:"request_type_url,omitempty"`
	// If true, the request is streamed.
	RequestStreaming bool `protobuf:"varint,3,opt,name=request_streaming,json=requestStreaming" json:"request_streaming,omitempty"`
	// The URL of the output message type.
	ResponseTypeUrl string `protobuf:"bytes,4,opt,name=response_type_url,json=responseTypeUrl" json:"response_type_url,omitempty"`
	// If true, the response is streamed.
	ResponseStreaming bool `protobuf:"varint,5,opt,name=response_streaming,json=responseStreaming" json:"response_streaming,omitempty"`
	// Any metadata attached to the method.
	Options []*Option `protobuf:"bytes,6,rep,name=options" json:"options,omitempty"`
	// The source syntax of this method.
	Syntax Syntax `protobuf:"varint,7,opt,name=syntax,enum=google.protobuf.Syntax" json:"syntax,omitempty"`
}

func (m *Method) Reset()                    { *m = Method{} }
func (m *Method) String() string            { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()               {}
func (*Method) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Method) GetOptions() []*Option {
	if m != nil {
		return m.Options
	}
	return nil
}

// Declares an API to be included in this API. The including API must
// redeclare all the methods from the included API, but documentation
// and options are inherited as follows:
//
// - If after comment and whitespace stripping, the documentation
//   string of the redeclared method is empty, it will be inherited
//   from the original method.
//
// - Each annotation belonging to the service config (http,
//   visibility) which is not set in the redeclared method will be
//   inherited.
//
// - If an http annotation is inherited, the path pattern will be
//   modified as follows. Any version prefix will be replaced by the
//   version of the including API plus the [root][] path if specified.
//
// Example of a simple mixin:
//
//     package google.acl.v1;
//     service AccessControl {
//       // Get the underlying ACL object.
//       rpc GetAcl(GetAclRequest) returns (Acl) {
//         option (google.api.http).get = "/v1/{resource=**}:getAcl";
//       }
//     }
//
//     package google.storage.v2;
//     service Storage {
//       rpc GetAcl(GetAclRequest) returns (Acl);
//
//       // Get a data record.
//       rpc GetData(GetDataRequest) returns (Data) {
//         option (google.api.http).get = "/v2/{resource=**}";
//       }
//     }
//
// Example of a mixin configuration:
//
//     apis:
//     - name: google.storage.v2.Storage
//       mixins:
//       - name: google.acl.v1.AccessControl
//
// The mixin construct implies that all methods in `AccessControl` are
// also declared with same name and request/response types in
// `Storage`. A documentation generator or annotation processor will
// see the effective `Storage.GetAcl` method after inherting
// documentation and annotations as follows:
//
//     service Storage {
//       // Get the underlying ACL object.
//       rpc GetAcl(GetAclRequest) returns (Acl) {
//         option (google.api.http).get = "/v2/{resource=**}:getAcl";
//       }
//       ...
//     }
//
// Note how the version in the path pattern changed from `v1` to `v2`.
//
// If the `root` field in the mixin is specified, it should be a
// relative path under which inherited HTTP paths are placed. Example:
//
//     apis:
//     - name: google.storage.v2.Storage
//       mixins:
//       - name: google.acl.v1.AccessControl
//         root: acls
//
// This implies the following inherited HTTP annotation:
//
//     service Storage {
//       // Get the underlying ACL object.
//       rpc GetAcl(GetAclRequest) returns (Acl) {
//         option (google.api.http).get = "/v2/acls/{resource=**}:getAcl";
//       }
//       ...
//     }
type Mixin struct {
	// The fully qualified name of the API which is included.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// If non-empty specifies a path under which inherited HTTP paths
	// are rooted.
	Root string `protobuf:"bytes,2,opt,name=root" json:"root,omitempty"`
}

func (m *Mixin) Reset()                    { *m = Mixin{} }
func (m *Mixin) String() string            { return proto.CompactTextString(m) }
func (*Mixin) ProtoMessage()               {}
func (*Mixin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Api)(nil), "google.protobuf.Api")
	proto.RegisterType((*Method)(nil), "google.protobuf.Method")
	proto.RegisterType((*Mixin)(nil), "google.protobuf.Mixin")
}

func init() { proto.RegisterFile("google/protobuf/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0xd1, 0xae, 0xd2, 0x30,
	0x18, 0xc7, 0xd3, 0x0d, 0x06, 0x96, 0x08, 0x5a, 0x13, 0xad, 0x5c, 0x90, 0x85, 0x78, 0xb1, 0x68,
	0xdc, 0x22, 0x3e, 0x01, 0x18, 0xc3, 0x05, 0x31, 0x2e, 0x43, 0xe3, 0x25, 0x19, 0x58, 0xb1, 0xc9,
	0xd6, 0xd6, 0xb6, 0x53, 0x78, 0x1b, 0xe3, 0xa5, 0x97, 0xe7, 0x0d, 0xce, 0x9b, 0x9d, 0xac, 0x5b,
	0x81, 0x33, 0x38, 0xc9, 0x39, 0x77, 0xfd, 0xfa, 0xff, 0x7d, 0xff, 0xf6, 0xfb, 0x7f, 0xf0, 0xe5,
	0x96, 0xf3, 0x6d, 0x46, 0x22, 0x21, 0xb9, 0xe6, 0xeb, 0xe2, 0x47, 0x94, 0x0a, 0x1a, 0x9a, 0x02,
	0x0d, 0x2a, 0x29, 0xb4, 0xd2, 0xf0, 0x55, 0x93, 0x55, 0xbc, 0x90, 0x1b, 0xb2, 0xda, 0x70, 0xa6,
	0xc9, 0x4e, 0x57, 0xe0, 0x70, 0xd8, 0xa4, 0xf4, 0x5e, 0xd4, 0x26, 0xe3, 0x6b, 0x07, 0xba, 0x53,
	0x41, 0x11, 0x82, 0x2d, 0x96, 0xe6, 0x04, 0x03, 0x1f, 0x04, 0x8f, 0x12, 0x73, 0x46, 0xef, 0x60,
	0x27, 0x27, 0xfa, 0x27, 0xff, 0xae, 0xb0, 0xe3, 0xbb, 0x41, 0x6f, 0xf2, 0x22, 0x6c, 0x7c, 0x20,
	0xfc, 0x64, 0xf4, 0xc4, 0x72, 0x65, 0x0b, 0x17, 0x9a, 0x72, 0xa6, 0xb0, 0x7b, 0x47, 0xcb, 0x67,
	0xa3, 0x27, 0x96, 0x43, 0x18, 0x76, 0x7e, 0x13, 0xa9, 0x28, 0x67, 0xb8, 0x65, 0x1e, 0xb7, 0x25,
	0xfa, 0x08, 0xfb, 0xb7, 0xe7, 0xc1, 0x6d, 0x1f, 0x04, 0xbd, 0xc9, 0xe8, 0xcc, 0x73, 0x69, 0xb0,
	0x0f, 0x15, 0x95, 0x3c, 0x56, 0xa7, 0x25, 0x0a, 0xa1, 0x97, 0xd3, 0x1d, 0x65, 0x0a, 0x7b, 0xe6,
	0x4b, 0xcf, 0xcf, 0xa7, 0x28, 0xe5, 0xa4, 0xa6, 0x50, 0x04, 0x3d, 0xb5, 0x67, 0x3a, 0xdd, 0xe1,
	0x8e, 0x0f, 0x82, 0xfe, 0x85, 0x11, 0x96, 0x46, 0x4e, 0x6a, 0x6c, 0x7c, 0xe5, 0x40, 0xaf, 0x0a,
	0xe2, 0x62, 0x8c, 0x01, 0x7c, 0x22, 0xc9, 0xaf, 0x82, 0x28, 0xbd, 0x2a, 0x83, 0x5f, 0x15, 0x32,
	0xc3, 0x8e, 0xd1, 0xfb, 0xf5, 0xfd, 0x97, 0xbd, 0x20, 0x5f, 0x65, 0x86, 0xde, 0xc0, 0xa7, 0x96,
	0x54, 0x5a, 0x92, 0x34, 0xa7, 0x6c, 0x8b, 0x5d, 0x1f, 0x04, 0xdd, 0xc4, 0x5a, 0x2c, 0xed, 0x3d,
	0x7a, 0x5d, 0xc2, 0x4a, 0x70, 0xa6, 0xc8, 0xd1, 0xb7, 0x4a, 0x70, 0x60, 0x05, 0x6b, 0xfc, 0x16,
	0xa2, 0x03, 0x7b, 0x74, 0x6e, 0x1b, 0xe7, 0x83, 0xcb, 0xd1, 0xfa, 0x64, 0x8b, 0xde, 0x3d, 0xb7,
	0xf8, 0xe0, 0xd0, 0x22, 0xd8, 0x36, 0xb1, 0x5f, 0x8c, 0x0c, 0xc1, 0x96, 0xe4, 0x5c, 0xd7, 0x31,
	0x99, 0xf3, 0x6c, 0x01, 0x9f, 0x6d, 0x78, 0xde, 0xb4, 0x9d, 0x75, 0xa7, 0x82, 0xc6, 0x65, 0x11,
	0x83, 0xbf, 0x00, 0xfc, 0x73, 0xdc, 0x79, 0x3c, 0xfb, 0xef, 0x8c, 0xe6, 0x15, 0x16, 0xdb, 0xd7,
	0xbf, 0x91, 0x2c, 0x5b, 0x30, 0xfe, 0x87, 0x95, 0x91, 0xa8, 0xb5, 0x67, 0xfa, 0xdf, 0xdf, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xa4, 0x45, 0xd6, 0xc6, 0x6d, 0x03, 0x00, 0x00,
}
