// Code generated by protoc-gen-go.
// source: google/api/consumer.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Supported data type of the property values
type Property_PropertyType int32

const (
	// The type is unspecified, and will result in an error.
	Property_UNSPECIFIED Property_PropertyType = 0
	// The type is `int64`.
	Property_INT64 Property_PropertyType = 1
	// The type is `bool`.
	Property_BOOL Property_PropertyType = 2
	// The type is `string`.
	Property_STRING Property_PropertyType = 3
	// The type is 'double'.
	Property_DOUBLE Property_PropertyType = 4
)

var Property_PropertyType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "INT64",
	2: "BOOL",
	3: "STRING",
	4: "DOUBLE",
}
var Property_PropertyType_value = map[string]int32{
	"UNSPECIFIED": 0,
	"INT64":       1,
	"BOOL":        2,
	"STRING":      3,
	"DOUBLE":      4,
}

func (x Property_PropertyType) String() string {
	return proto.EnumName(Property_PropertyType_name, int32(x))
}
func (Property_PropertyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{1, 0} }

// A descriptor for defining project properties for a service. One service may
// have many consumer projects, and the service may want to behave differently
// depending on some properties on the project. For example, a project may be
// associated with a school, or a business, or a government agency, a business
// type property on the project may affect how a service responds to the client.
// This descriptor defines which properties are allowed to be set on a project.
//
// Example:
//
//    project_properties:
//      properties:
//      - name: NO_WATERMARK
//        type: BOOL
//        description: Allows usage of the API without watermarks.
//      - name: EXTENDED_TILE_CACHE_PERIOD
//        type: INT64
type ProjectProperties struct {
	// List of per consumer project-specific properties.
	Properties []*Property `protobuf:"bytes,1,rep,name=properties" json:"properties,omitempty"`
}

func (m *ProjectProperties) Reset()                    { *m = ProjectProperties{} }
func (m *ProjectProperties) String() string            { return proto.CompactTextString(m) }
func (*ProjectProperties) ProtoMessage()               {}
func (*ProjectProperties) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *ProjectProperties) GetProperties() []*Property {
	if m != nil {
		return m.Properties
	}
	return nil
}

// Defines project properties.
//
// API services can define properties that can be assigned to consumer projects
// so that backends can perform response customization without having to make
// additional calls or maintain additional storage. For example, Maps API
// defines properties that controls map tile cache period, or whether to embed a
// watermark in a result.
//
// These values can be set via API producer console. Only API providers can
// define and set these properties.
type Property struct {
	// The name of the property (a.k.a key).
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The type of this property.
	Type Property_PropertyType `protobuf:"varint,2,opt,name=type,enum=google.api.Property_PropertyType" json:"type,omitempty"`
	// The description of the property
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *Property) Reset()                    { *m = Property{} }
func (m *Property) String() string            { return proto.CompactTextString(m) }
func (*Property) ProtoMessage()               {}
func (*Property) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func init() {
	proto.RegisterType((*ProjectProperties)(nil), "google.api.ProjectProperties")
	proto.RegisterType((*Property)(nil), "google.api.Property")
	proto.RegisterEnum("google.api.Property_PropertyType", Property_PropertyType_name, Property_PropertyType_value)
}

func init() { proto.RegisterFile("google/api/consumer.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4f, 0x83, 0x30,
	0x18, 0xc6, 0xed, 0x86, 0xcb, 0xf6, 0xa2, 0x13, 0xdf, 0x78, 0xc0, 0x1b, 0xe3, 0xc4, 0x89, 0x25,
	0x73, 0xfa, 0x01, 0xd8, 0xd0, 0x34, 0x21, 0xd0, 0x30, 0xf6, 0x01, 0x10, 0x9b, 0xa5, 0x46, 0x68,
	0x53, 0xea, 0x81, 0x0f, 0xe8, 0xf7, 0x32, 0xc3, 0x39, 0x39, 0x78, 0x7b, 0xda, 0xe7, 0x4f, 0xde,
	0xfc, 0xe0, 0xfe, 0x20, 0xe5, 0xe1, 0x83, 0x2f, 0x4b, 0x25, 0x96, 0x95, 0x6c, 0xda, 0xcf, 0x9a,
	0xeb, 0x50, 0x69, 0x69, 0x24, 0xc2, 0x8f, 0x15, 0x96, 0x4a, 0xf8, 0x14, 0x6e, 0x99, 0x96, 0xef,
	0xbc, 0x32, 0x4c, 0x4b, 0xc5, 0xb5, 0x11, 0xbc, 0xc5, 0x35, 0x80, 0x3a, 0xbf, 0x5c, 0xe2, 0x8d,
	0x03, 0x7b, 0x75, 0x17, 0xfe, 0xb5, 0xc2, 0x53, 0xb6, 0xcb, 0x07, 0x39, 0xff, 0x8b, 0xc0, 0xf4,
	0xd7, 0x40, 0x04, 0xab, 0x29, 0x6b, 0xee, 0x12, 0x8f, 0x04, 0xb3, 0xbc, 0xd7, 0xf8, 0x08, 0x96,
	0xe9, 0x14, 0x77, 0x47, 0x1e, 0x09, 0xe6, 0xab, 0xc5, 0x7f, 0x83, 0x67, 0x51, 0x74, 0x8a, 0xe7,
	0x7d, 0x1c, 0x3d, 0xb0, 0xdf, 0x78, 0x5b, 0x69, 0xa1, 0x8c, 0x90, 0x8d, 0x3b, 0xee, 0x17, 0x87,
	0x5f, 0x7e, 0x02, 0x57, 0xc3, 0x1e, 0xde, 0x80, 0xbd, 0x4f, 0x77, 0x2c, 0xde, 0xd0, 0x67, 0x1a,
	0x6f, 0x9d, 0x0b, 0x9c, 0xc1, 0x25, 0x4d, 0x8b, 0xa7, 0xb5, 0x43, 0x70, 0x0a, 0x56, 0x94, 0x65,
	0x89, 0x33, 0x42, 0x80, 0xc9, 0xae, 0xc8, 0x69, 0xfa, 0xe2, 0x8c, 0x8f, 0x7a, 0x9b, 0xed, 0xa3,
	0x24, 0x76, 0xac, 0x68, 0x01, 0xf3, 0x4a, 0xd6, 0x83, 0xeb, 0xa2, 0xeb, 0xcd, 0x09, 0x20, 0x3b,
	0xf2, 0x63, 0xe4, 0x75, 0xd2, 0x83, 0x7c, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x79, 0x08,
	0xd2, 0x65, 0x01, 0x00, 0x00,
}
