#!/bin/bash
#
# Copyright (C) Endpoints Server Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#

# This script manipulates Google App Engine applications.
# It supports deploying an application, deleting it,
# and fetching backend NGINX logs from the managed virtual machines.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${ROOT}/script/all-utilities || { echo "Cannot load Bash utilities"; exit 1; }

function usage() {
  [[ -n "${1}" ]] && echo "${1}"

  cat <<EOF
usage: ${BASH_SOURCE[0]} [options ...] <command>"

  <command> is one of:
    deploy|create: Creates and deploys a managed VM application.
    delete: Deletes deployed managed VM application.
    nginx-logs: Download NGINX logs from the managed VM.

  options:
    -g ... path to gcloud tool (default 'gcloud')
    -s ... path to gsutil tool (default 'gsutil')
    -a ... path to the application's app.yaml file (required)
    -v ... application version to deploy in GAE
    -s ... app engine service (module) to use for deployment (default 'default')
    -p ... project id of the target project (default 'esp-load-test')
    -d ... target directory for the NGINX logs (default '/tmp/nginx-logs')
EOF
  exit 2
}

GCLOUD='gcloud'
GSUTIL='gsutil'
APP_YAML_FILE=""
VERSION=""
SERVICE="default"
PROJECT="esp-load-test"
LOG_DIRECTORY="/tmp/nginx-logs"

while getopts :g:a:v:s:p:d: arg; do
  case ${arg} in
    g) GCLOUD="${OPTARG}";;
    a) APP_YAML_FILE="${OPTARG}";;
    v) VERSION="${OPTARG}";;
    s) SERVICE="${OPTARG}";;
    p) PROJECT="${OPTARG}";;
    d) LOG_DIRECTORY="${OPTARG}";;
    *) usage "Invalid option: -${OPTARG}";;
  esac
done

shift $((OPTIND-1))
COMMAND="$1"

function deploy_application() {
  echo "Deploy GAE instace ${APP_YAML_FILE} to ${VERSION}"

  APP_DIR="$(dirname ${APP_YAML_FILE})"

  local ARGS=()
  [[ -n "${VERSION}" ]] && ARGS+=(--version "${VERSION}")

  (
    # deploying an endpoints app requires the current directory
    # to be the app directory
    cd "${APP_DIR}"
    ${GCLOUD} --project "${PROJECT}" preview app deploy \
      "${APP_YAML_FILE}" "${ARGS[@]}" --no-promote -q
  )
}

function delete_application() {
  echo "Delete GAE instace ${VERSION}"

  ${GCLOUD} --project "${PROJECT}" preview app versions delete \
    ${VERSION} --service ${SERVICE} -q
}

function set_ssh_keys() {
  local user="$(whoami)"
  local remote_ssh_keys="gs://${PROJECT}.appspot.com/ssh_keys/${user}"
  local local_ssh_keys="${HOME}/.ssh"
  local private_ssh_key="${local_ssh_keys}/google_compute_engine"
  if ! [[ -a "${private_ssh_key}" ]]; then
    ${GSUTIL} stat "${remote_ssh_keys}/google_compute_engine"
    if [[ ${?} -eq 0 ]]; then
      mkdir -p "${local_ssh_keys}" \
        || error_exit "Cannot create ${local_ssh_keys}"
      echo "Getting ssh key from ${remote_ssh_keys}"
      retry -n 3 ${GSUTIL} cp "${remote_ssh_keys}/*" "${local_ssh_keys}/" \
        || error_exit "Could not set ssh keys"
      echo "Setting right permssion on ${local_ssh_keys}"
      chmod -R 700 "${local_ssh_keys}"
    else
      echo 'Generating new ssh keys...'
      ${GCLOUD} --project ${PROJECT} compute config-ssh -q || \
        error_exit 'Unable to generate ssh keys'
      echo "Uploading new ssh keys to ${remote_ssh_keys}"
      ${GSUTIL} -h "Content-Type:text/plain" -m cp "${private_ssh_key}*" \
        "${remote_ssh_keys}/" \
        || error_exit "Failed to upload ssh keys to ${remote_ssh_keys}"
    fi
  fi
}

function download_nginx_logs() {
  local vm_id vm_zone vm_name

  [[ -n "${VERSION}" ]] \
    || error_exit "No version specified to download logs. Aborting."

  # If the output format is changed, we will fail to extract fields.
  # Here the output is always printed for easy debug.
  ${GCLOUD} preview app instances list \
      --project "${PROJECT}" --service "${SERVICE}" --version "${VERSION}" \
      --format json > $ROOT/instance-list
  echo "Instance list:"
  cat $ROOT/instance-list
  read vm_id vm_zone vm_name < <(cat $ROOT/instance-list \
    | python "${ROOT}/script/find-gae-backend-vm-name.py")

  [[ -n "${vm_id}" && -n "${vm_zone}" && -n "${vm_name}" ]] \
    || error_exit "Cannot identify backend VM name and zone. Aborting."

  ${GCLOUD} preview app instances enable-debug ${vm_id} \
          --service "${SERVICE}" --version "${VERSION}" \
          --project ${PROJECT} -q \
    || error_exit "Cannot enable-debug on the managed VM. Aborting."

  mkdir -p "${LOG_DIRECTORY}"

  local archive_path="${LOG_DIRECTORY}/${VERSION}.tar.gz"

  set_ssh_keys

  ${GCLOUD} compute ssh --project=${PROJECT} --zone=${vm_zone} \
      ${vm_name} sudo tar csf - /var/log/ > "${archive_path}" \
    || error_exit "Cannot copy logs from the backend VM."

}

# Current gcloud account may not have permission to deploy an GAE Flex
# application in an esp-load-test project. The following will activate
# esp-load-test service account.
if [[ "${PROJECT}" == "esp-load-test" ]]; then
    echo "Gcloud auth activate esp-load-test service account"
    gsutil cp gs://client-secret-files/esp-load-test-08fcbb64ace1.json /tmp/client.json
    gcloud auth activate-service-account --key-file /tmp/client.json
    trap 'gcloud auth revoke service-control-in-load-test@esp-load-test.iam.gserviceaccount.com' EXIT
fi

if [[ "${PROJECT}" == "esp-long-run" ]]; then
    echo "Gcloud auth activate esp-long-run service account"
    gsutil cp gs://client-secret-files/esp-long-run-f92945d40e0b.json /tmp/client.json
    gcloud auth activate-service-account --key-file /tmp/client.json
    trap 'gcloud auth revoke deploy-esp-vm@esp-long-run.iam.gserviceaccount.com' EXIT
fi

case "${COMMAND}" in
  create | deploy)  retry -n 5 -s 10 deploy_application;;
  delete         )  delete_application;;
  nginx-logs     )  download_nginx_logs;;
  *              )  usage "Unknown command ${COMMAND}."
esac

