#!/bin/bash
#
# Copyright (C) Extensible Service Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${ROOT}/script/all-utilities || { echo "Cannot load Bash utilities"; exit 1; }

function usage() {
  [[ -n "${1}" ]] && echo "${1}"
  cat <<EOF
usage: ${BASH_SOURCE[0]} -s <release SHA> -n <next version number>"

This script will create a new release branch with the SHA.
Then update the version number for next release and push for review.

example:
${BASH_SOURCE[0]} \\
    -n 1.2.0 \\
    -s be2eb101f1b1b3e671e852656066c2909c41049b
EOF
  exit 1
}

# Create a branch for release.
NEXT_VERSION=''
SHA=''

while getopts :n:s: arg; do
  case ${arg} in
    n) NEXT_VERSION="${OPTARG}";;
    s) SHA="${OPTARG}";;
    *) usage "Invalid option: -${OPTARG}";;
  esac
done

[[ -n "${NEXT_VERSION}" ]] \
  || usage "Please provide the next release version."
# The version format is: 1.2.0
[[ "${NEXT_VERSION}" =~ [0-9]+\.[0-9]+\.0 ]] \
  || usage "Invalid version number: ${NEXT_VERSION}."
[[ -n "${SHA}" ]] \
  || usage "Please provide the release SHA."

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
VERSION="$(command cat ${ROOT}/src/nginx/version)"
# If version name is 1.0.0, the release branch name is: v1.0.x
RELEASE_BRANCH=v${VERSION%.0}.x
echo "Current branch: ${CURRENT_BRANCH}."
echo "New release branch: ${RELEASE_BRANCH}."
[[ -z $(git diff --name-only) ]] \
  || error_exit "Current branch is not clean."

git fetch origin \
  || error_exit "Could not fetch origin."
git branch ${RELEASE_BRANCH} ${SHA} \
  || error_exit "Could not create a local release branch."
git push origin ${SHA}:refs/heads/${RELEASE_BRANCH} \
  || error_exit "Failed to create a remote release branch."

# Update the version number and push for review.
git checkout origin/master
echo "${NEXT_VERSION}" > ${ROOT}/src/nginx/version
git add ${ROOT}/src/nginx/version
git commit -m "Update version number to ${NEXT_VERSION}."
git push origin HEAD:refs/for/refs/heads/master

git checkout ${RELEASE_BRANCH}

printf '\e[31m
***************************************************************************
*      Please paste the script output verbatim into the release bug.      *
***************************************************************************
\e[0m'
