#!/bin/bash
#
# Copyright (C) Endpoints Server Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#

RELEASE_TAR=""
RELEASE_DEB=""
VERSIONED_DEB=""
RELEASE_JSON=""
SKIP_TESTS="false"

# Generic docker image format. Docker image name is computed using:
# git show -q HEAD --pretty=format:"${RELEASE_FLEX_IMAGE_FORMAT}"
# The format string can therefore contain format placeholders:
# https://git-scm.com/docs/git-show
RELEASE_FLEX_IMAGE_FORMAT="gcr.io/endpointsv2/endpoints-runtime-flex:debian-git-%H"
RELEASE_GENERIC_IMAGE_FORMAT="gcr.io/endpointsv2/endpoints-runtime"
RELEASE_GENERIC_IMAGE_FORMAT+=":debian-git-%H"
RELEASE_GENERIC_GRPC_IMAGE_FORMAT="gcr.io/endpointsv2/endpoints-runtime-grpc"
RELEASE_GENERIC_GRPC_IMAGE_FORMAT+=":debian-git-%H"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${ROOT}/script/all-utilities || { echo "Cannot load Bash utilities"; exit 1; }

CONFIG=''

while getopts :c:d:f:g:j:m:st:v: arg; do
  case ${arg} in
    c) CONFIG="${OPTARG}";;
    d) RELEASE_DEB="${OPTARG}";;
    f) RELEASE_FLEX_IMAGE_FORMAT="${OPTARG}";;
    g) RELEASE_GENERIC_IMAGE_FORMAT="${OPTARG}";;
    j) RELEASE_JSON="${OPTARG}";;
    m) RELEASE_FLEX_IMAGE_FORMAT="${OPTARG}";;
    s) SKIP_TESTS="true";;
    t) RELEASE_TAR="${OPTARG}";;
    v) VERSIONED_DEB="${OPTARG}";;
    *) echo "Invalid argument -${OPTARG}, ignoring.";;
  esac
done

[[ -n "${CONFIG}" ]] \
  && CONFIG="${ROOT}/${CONFIG}" \
  && echo "Using server config ${CONFIG}"

( echo "Building and installing dependencies."
  ${ROOT}/script/linux-build-dependencies \
    || error_exit "Failed to build and install dependencies."
) || error_exit "Build of dependencies failed."

bazel clean \
  || error_exit "Failed to bazel clean before the release build."

if [[ "${SKIP_TESTS}" == "false" ]]; then
  echo "Running pre-release tests."
  bazel test --config=release \
      //src/... \
      //third_party:all \
    || error_exit "Failed release tests."
fi

read ENDPOINTS_RUNTIME_VERSION < ${ROOT}/include/version
BAZEL_VERSION="$(bazel version | grep '^Build label: ' | sed 's/^Build label: //')"
echo "Bazel ${BAZEL_VERSION}" > "${ROOT}/src/nginx/main/built_using"
DEB="${ROOT}/bazel-bin/src/nginx/main/endpoints-server-proxy.deb"
# Placeholder for debian package.
TMP_DEBIAN_PACKAGE="$(mktemp /tmp/XXXXXX.deb)"

if [[ -n "${RELEASE_DEB}" ]]; then
  echo "Attempting to download ${RELEASE_DEB}."
  rm -f "${TMP_DEBIAN_PACKAGE}"
  gsutil cp "${RELEASE_DEB}" "${TMP_DEBIAN_PACKAGE}" \
    || echo "Failed to download ${RELEASE_DEB}. Building it."
fi

if ! [[ -e "${TMP_DEBIAN_PACKAGE}" ]]; then
  echo "Building Endpoints Runtime .deb package."
  bazel build --config=release //src/nginx/main:endpoints-server-proxy \
    || error_exit "Failed to build Endpoints Runtime .deb package."

  if [[ -n "${RELEASE_DEB}" ]]; then
    echo "Uploading ${DEB} to ${RELEASE_DEB}"
    retry -n 3 gsutil -h Content-Type:application/x-deb cp \
        ${DEB} \
        ${RELEASE_DEB} \
      || error_exit "Debian package upload failed."
  fi
  cp -f "${DEB}" "${TMP_DEBIAN_PACKAGE}" \
    || error_exit "Could not copy ${DEB} to ${TMP_DEBIAN_PACKAGE}"
fi

# Compute .deb name if not provided.
if [[ -z "${VERSIONED_DEB}" && -n "${RELEASE_DEB}" ]]; then
  VERSIONED_DEB="${RELEASE_DEB%.deb}-precise.deb"
fi

if [[ -n "${VERSIONED_DEB}" ]]; then
  echo "Attempting to download ${VERSIONED_DEB}."
  rm -f ${TMP_DEBIAN_PACKAGE}
  gsutil cp "${VERSIONED_DEB}" "${TMP_DEBIAN_PACKAGE}" \
    || echo "Failed to download ${VERSIONED_DEB}. Building it."
fi

if ! [[ -e "${TMP_DEBIAN_PACKAGE}" ]]; then
  echo "Building Endpoints Runtime verbatim version .deb package."
  COMMITS=$(git rev-list HEAD | wc -l)
  SHA=$(git rev-parse --short HEAD)
  echo "${ENDPOINTS_RUNTIME_VERSION}~${COMMITS}.${SHA}" \
    > ${ROOT}/include/version

  cat <<__EOF__ >> ${ROOT}/src/nginx/main/description
 .
 .
  Version: ${ENDPOINTS_RUNTIME_VERSION}
  Commit: $(git rev-parse HEAD)
__EOF__

  bazel build --config=release //src/nginx/main:endpoints-server-proxy \
    || error_exit "Failed to build Endpoints Runtime verbatim version .deb package."

  if [[ -n "${VERSIONED_DEB}" ]]; then
    echo "Uploading ${DEB} to ${VERSIONED_DEB}"
    retry -n 3 gsutil -h Content-Type:application/x-deb cp \
        ${DEB} \
        ${VERSIONED_DEB} \
      || error_exit "Debian package upload failed."
  fi

  cp -f "${DEB}" "${TMP_DEBIAN_PACKAGE}" \
    || error_exit "Could not copy ${DEB} to ${TMP_DEBIAN_PACKAGE}"

fi

# Build docker container image for FLEX deployment.
if [[ -n "${RELEASE_FLEX_IMAGE_FORMAT}" ]]; then
  FLEX_IMAGE="$(git show -q HEAD --pretty=format:"${RELEASE_FLEX_IMAGE_FORMAT}")"
  ${ROOT}/script/linux-build-docker -d "${TMP_DEBIAN_PACKAGE}" -i "${FLEX_IMAGE}" -p flex \
    || error_exit "Failed to build a Flex Docker Image."
fi

# Build docker container image for GKE/GCE deployment.
if  [[ -n "${RELEASE_GENERIC_IMAGE_FORMAT}" ]]; then
  GENERIC_IMAGE="$(git show -q HEAD --pretty=format:"${RELEASE_GENERIC_IMAGE_FORMAT}")"
  ${ROOT}/script/linux-build-docker -c "${CONFIG}" -d "${TMP_DEBIAN_PACKAGE}" -i "${GENERIC_IMAGE}" -p generic \
    || error_exit "Failed to build a generic Docker Image."
fi

# Build docker container image for GKE/GCE deployment with GRPC backend.
if  [[ -n "${RELEASE_GENERIC_GRPC_IMAGE_FORMAT}" ]]; then
  GENERIC_GRPC_IMAGE="$(git show -q HEAD --pretty=format:"${RELEASE_GENERIC_GRPC_IMAGE_FORMAT}")"
  ${ROOT}/script/linux-build-docker -c "${CONFIG}" -d "${TMP_DEBIAN_PACKAGE}" -g -i "${GENERIC_GRPC_IMAGE}" -p generic \
    || error_exit "Failed to build a grpc Docker Image."
fi

if [[ -n "${RELEASE_JSON}" ]]; then
  {
    echo "Uploading results to ${RELEASE_JSON}."
    retry -n 3 gsutil -h Content-Type:application/json cp - "${RELEASE_JSON}" <<__EOF__
{
  "docker": "${FLEX_IMAGE}",
  "flexDocker": "${FLEX_IMAGE}",
  "genericDocker": "${GENERIC_IMAGE}",
  "releaseDeb": "${RELEASE_DEB}",
  "versionedDeb": "${VERSIONED_DEB}"
}
__EOF__
  } || error_exit "Docker status upload failed."
fi

