#!/bin/bash
#
# Copyright (C) Extensible Service Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#

TEST_JSON=""
TEST_DOCKER=""
TEST_DURATION=""
KEEP_BACKEND_APP=""
GAE_VERSION=""
BUCKET=""

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

while getopts :b:j:d:l:kv: arg; do
  case ${arg} in
    b) BUCKET="${OPTARG}";;
    j) TEST_JSON="${OPTARG}";;
    d) TEST_DOCKER="${OPTARG}";;
    l) TEST_DURATION="${OPTARG}";;
    k) KEEP_BACKEND_APP="-k";;
    v) GAE_VERSION="${OPTARG}";;
    *) echo "Invalid option: -${OPTARG}" ; exit 1 ;;
  esac
done

${DIR}/linux-build-dependencies \
  || error_exit "Failed to build and install dependencies."

# Set default bucket until Robot serves it to us.
[[ -n "${BUCKET}" ]] || BUCKET="gs://endpoints-robot-temp/$(git show -q HEAD --pretty=format:%H)"

# Construct an array of arguments.
ARGS=(-e)
[[ -n "${TEST_DOCKER}" ]]      && ARGS+=(-i "${TEST_DOCKER}")
[[ -n "${GAE_VERSION}" ]]      && ARGS+=(-v "${GAE_VERSION}")
[[ -n "${KEEP_BACKEND_APP}" ]] && ARGS+=("${KEEP_BACKEND_APP}")
[[ "${TEST_DURATION}" -ge 0 ]] && ARGS+=(-l "${TEST_DURATION}")
[[ -n "${BUCKET}" ]]           && ARGS+=(-b "${BUCKET}")

${DIR}/linux-test-vm-bookstore "${ARGS[@]}" \
  || error_exit "Long run stress test failed."
