#!/bin/bash
#
# Copyright (C) Endpoints Server Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#

PERFORMANCE_JSON=""
PERFORMANCE_ENV=""

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

while getopts j:e:t:b arg; do
  case ${arg} in
    j) PERFORMANCE_JSON=${OPTARG};;
    e) PERFORMANCE_ENV=${OPTARG};;
    t) echo "-t is deprecated and a noop";;
    b) echo "-b is deprecated and a noop";;
    ?) exit 1;;
  esac
done

${DIR}/linux-build-dependencies \
  || error_exit "Failed to build and install dependencies."

${DIR}/linux-install-test-client \
  || error_exit "Cannot install test client."

${DIR}/linux-start-local-test -t "${PERFORMANCE_ENV}" \
  || error_exit "Local test failed."
