#!/bin/bash
#
# Copyright (C) Endpoints Server Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${ROOT}/script/jenkins-utilities || { echo "Cannot load jenkins-utilities"; exit 1; }

BUILD_URL=''
CHANGE_ID=''
GIT_COMMIT=''
REPO_URL=''
STATUS='Failed'
VERIFIED='-1'

while getopts :b:c:r:s:v arg; do
  case ${arg} in
    b) BUILD_URL="${OPTARG}";;
    c) CHANGE_ID="${OPTARG}";;
    r) REPO_URL="${OPTARG}"
    s) GIT_COMMIT="${OPTARG}";;
    v)
      VERIFIED='+1'
      STATUS='Successful';;
    *) echo "Invalid option: -${OPTARG}";;
  esac
done

[[ -n "${BUILD_URL}" ]] || error_exit 'BUILD_URL needs to be set with b'
[[ -n "${CHANGE_ID}" ]] || error_exit 'CHANGE_ID needs to be set with -c.'
[[ -n "${GIT_COMMIT}" ]] || error_exit 'GIT_COMMIT needs to be set with -s.'
[[ -n "${REPO_URL}" ]] || error_exit 'REPO_URL needs to be set with -r.'

REVIEW_ENDPOINT="$REPO_URL/a/changes/$CHANGE_ID/revisions/$GIT_COMMIT/review/"

MESSAGE="${STATUS} Presubmits. More info at ${BUILD_URL}"

curl -b ~/.gitcookies \
  -X POST \
  -H "Content-Type: application/json" \
  --url $REVIEW_ENDPOINT \
  -d @- <<EOF
{
  "message": "$MESSAGE",
  "labels": {
    "Verified": $VERIFIED
  }
}
EOF

