# ESP Proxy that forwards requests into the application server.

FROM ${PARENT_IMAGE}

ADD server_config.cfg /etc/nginx/server_config.cfg
ADD nginx.conf.template /etc/nginx/nginx.conf.template

# to run nginx that proxies the requests to server at HOST:PORT
# docker run -p 8080:8080 --expose 8090 \
#   --entrypoint=/var/lib/nginx/bin/start_nginx.sh -a HOST:PORT

# ENTRYPOINT ["/var/lib/nginx/bin/start_nginx.sh"]
