#!/bin/bash
#
# Copyright (C) Extensible Service Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#
# May require sudo login.

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

BAZEL_VERSION='0.4.3'
BAZEL_BASE_URL='https://github.com/bazelbuild/bazel/releases/download'
BAZEL_SH="bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh"
BAZEL_URL="${BAZEL_BASE_URL}/${BAZEL_VERSION}/${BAZEL_SH}"
BAZEL_DIRECTORY="${TOOLS_DIR}/bazel"

function update_bazel() {
  local bazel_current="$(bazel version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')" \
    || bazel_current='none'

  if [[ -d "${BAZEL_DIRECTORY}" ]]; then
    mkdir -p "${BAZEL_DIRECTORY}"
  fi

  if [[ "${BAZEL_VERSION}" != "${bazel_current}" ]]; then
    retry -n 3 wget -q -nc -P "${BAZEL_DIRECTORY}" "${BAZEL_URL}" \
      || error_exit "Could not download bazel"
    chmod +x "${BAZEL_DIRECTORY}/${BAZEL_SH}" \
      || error_exit "Could not mark bazel shell as executable"
    ${SUDO} "${BAZEL_DIRECTORY}/${BAZEL_SH}" \
      || error_exit "Could not install bazel"
    set_bazel
  fi
  echo 'Bazel up-to-date.'
}

