#!/bin/bash
#
# Copyright (C) Extensible Service Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#
# May require sudo login.

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

CLANG_VERSION='3.8'

function install_clang() {
  echo 'Installing clang'
  clear_apt \
  && ${SUDO} apt-get -qqy install {clang,clang-format}-"${CLANG_VERSION}" \
  && ${SUDO} cp -f "/usr/bin/clang-${CLANG_VERSION}" /usr/bin/clang \
  && ${SUDO} cp -f "/usr/bin/clang++-${CLANG_VERSION}" /usr/bin/clang++ \
  && ${SUDO} cp -f "/usr/bin/clang-format-${CLANG_VERSION}" /usr/bin/clang-format \
  && return 0
  return 1
}

function update_clang() {
  local version="$(clang --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')"
  if ! [[ "${version}" =~ "${CLANG_VERSION}" ]]; then
    retry install_clang || error_exit 'Cannot install clang.'
  fi
  echo 'Clang is up to date.'
}

function install_clang_format_7() {
   echo 'Installing clang'
  ${SUDO} wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - \
  && ${SUDO} apt-add-repository "deb https://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main" \
  && ${SUDO} apt update \
  && ${SUDO} apt -qqy install clang-format-7 \
  && return 0
  return 1
}
