#!/bin/bash
#
# Copyright (C) Extensible Service Proxy Authors
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
################################################################################
#
# May require sudo login.

if [[ "$(uname)" != "Linux" ]]; then
  echo "Run on Linux only."
  exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. ${DIR}/all-utilities || { echo "Cannot load Bash utilities" ; exit 1 ; }

NODE_JS_VERSION='4.6.1'
NODE_JS_ARCHIVE="node-v${NODE_JS_VERSION}-linux-x64.tar.xz"
NODE_JS_URL="https://nodejs.org/dist/v${NODE_JS_VERSION}/${NODE_JS_ARCHIVE}"
NODE_JS_DIRECTORY="${TOOLS_DIR}/nodejs"

function update_node_js() {
  local version="$(node --version | grep -oh '[0-9]*\.[0-9]*\.[0-9]*')"

  if [[ -d "${NODE_JS_DIRECTORY}" ]]; then
    mkdir -p "${NODE_JS_DIRECTORY}"
  fi

  if [[ "${version}" != "${NODE_JS_VERSION}" ]]; then
    echo 'Installing Node.js and npmV.'
    retry -n 3 wget -q -nc -P "${NODE_JS_DIRECTORY}" "${NODE_JS_URL}" \
      || error_exit 'Could not download nodejs'
    ${SUDO} tar -C /usr/local --strip-components 1 -xf \
      "${NODE_JS_DIRECTORY}/${NODE_JS_ARCHIVE}" \
      || error_exit 'Could not extract nodejs archive'
  fi
  echo 'Node.js is up to date.'
}
